version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: oraclelinux:7.6
    steps:
      - checkout
      - run:
          name: test cloud-init standard
          command: sudo bash ./OCI/RHEL/standard-setting.sh

  test:
    working_directory: ~/workspace
    docker:
      - image: oraclelinux:7.6
    steps:
      - checkout
      - run:
          name: test cloud-init docker
          command: sudo bash ./OCI/RHEL/docker-setting.sh
