version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: oraclelinux:7.6
        user: root
    steps:
      - checkout
      - run:
          name: install sudo
          command: yum install -y sudo
      - run:
          name: test cloud-init standard
          command: bash ./OCI/RHEL/standard-setting.sh

  test:
    working_directory: ~/workspace
    docker:
      - image: oraclelinux:7.6
        user: root
    steps:
      - checkout
      - run:
          name: install sudo
          command: yum install -y sudo
      - run:
          name: test cloud-init docker
          command: bash ./OCI/RHEL/docker-setting.sh
